# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "transport_lib",
    srcs = ["EventLoop.cc"],
    hdrs = ["EventLoop.h"],
    deps = ["@org_libevent_libevent//:libevent"],
)